### ISSUE TITLE
Botones de Aceptar y Cancelar en Preferencias no funcionan

### ISSUE THREAD

**Issue by Adrian-Benavente** [atareao/todotxt-indicator#10]
Escenario:

1. Voy a la opción de Preferencias desde el menú de la barra de tareas
2. Borro un proyecto, contexto o etiqueta
3. Pulso Aceptar o Cancelar
4. Cierro la ventana desde la cruz (x)

Error:

1. Los botones Aceptar y Cancelar no responden.
2. Luego de cerrar la ventana dándole a la cruz (x), la opción Preferencias aparece deshabilitada en el menú de la barra de tareas.

Entorno: KDE Neon 5.18

Adjunto video

![tasker-bug-2020-05-01_17 32 09](https://user-images.githubusercontent.com/11258517/80840616-12070900-8bd4-11ea-92af-e48d426bf52e.gif)

**Comment by flachica** [comment]
Eso lo resoví en este [PR](https://github.com/atareao/tasker/pull/8). Más concretamente en este [commit](https://github.com/atareao/tasker/pull/8/commits/c7ab5dbb78a9fa7e2079dee2a4d9c05663d79b3d)

**Comment by Adrian-Benavente** [comment]
@flachica por qué podría ser que aun no me haya entrado ese update?

**Comment by flachica** [comment]
Porque primero se debe aceptar la solución como válida, mejorarla en lo que sea posible, mezclar el código fuente de mi PR con el principal y después empaquetar y publicar. 

Como puedes ver es un proceso que lleva su tiempo. Informarte de que la propuesta de mejora ya está en el código principal, así que pronto se anunciará una actualización nueva. Todo eso lo lleva @atareao

**Comment by atareao** [comment]
Ya está subida la actualización al repositorio @Adrian-Benavente @flachica 
Gracias

**Comment by Adrian-Benavente** [comment]
¡A ustedes por el gran trabajo!

**Comment by flachica** [comment]
¿Podemos cerrar esta Issue?

**Comment by atareao** [comment]
Yo creo que está resueltoa, si vuelve a a parecer... pues ser reporta de nuevo
