### ISSUE TITLE
Incorrect resizing new task window

### ISSUE THREAD

**Issue by metrolan** [atareao/todotxt-indicator#15]
LinuxMint 19.3 Cinnamon, new task window doesn't shows all the items and can't be resized.

![image](https://user-images.githubusercontent.com/13301193/81489372-e095d980-9274-11ea-9b62-8d8edeed802f.png)

**Comment by atareao** [comment]
Fixed in 0.4.0

**Comment by atareao** [comment]
Thanks @metrolan
