### ISSUE TITLE
Ventana 'Lista de tareas' no deja redimensionar

### ISSUE THREAD

**Issue by Montsemg** [atareao/todotxt-indicator#16]
En la ventana 'Lista de tareas' no me deja redimensionar la ventana, los botones Aceptar y Cancelar quedan "fuera de alcance" 

Trabajo con dos monitores:

- Monitor (portátil) Resolución: 1366 x 768 (16:9)

- Monitor Resolución: 1280 x 1024 (5:4)

He probado varias combinaciones (2, 1, cambiar monitor principal, sólo 1,...) , en el monitor 1280 x 1024, se ve la ventana entera sin problemas pero en la pantalla del portátil, independientemente de la combinación que haga con los monitores, no deja acceder a los botones.

(Ubuntu 18.04.4 LTS)

**Comment by atareao** [comment]
Fixed in 0.4.0 Gracias @Montsemg
