### ISSUE TITLE
Ventana 'Editar tarea' el título de la ventana no se corresponde

### ISSUE THREAD

**Issue by Montsemg** [atareao/todotxt-indicator#17]
La ventana 'Editar tarea' cuando desde la lista de tareas selecciono una para pinchar y editar, se abre para modificarla aunque en el encabezado de la ventana pone 'Añadir tarea' no Editar.

Ubuntu 18.04.4 LTS

**Comment by atareao** [comment]
Fixed in 0.4.0 Thans @Montsemg
