### ISSUE TITLE
Sustitución de algunos caracteres (^,', ~) por "_"

### ISSUE THREAD

**Issue by Montsemg** [atareao/todotxt-indicator#18]
En Prefencias > Proyectos / Contextos 

No reconoce los acentos agudos ni la virgula/virgulilla, los sustituye por '_'

ejemplos:

- ingl_s en vez de inglés o 

- sess_oes en vez de sessões)

 El acento circunflejo lo reconoce unas veces sí y otras no. Por ejemplo, unas veces muestra _Portugu_s_ y otras  _Português_

(Ubuntu 18.04.4 LTS)

**Comment by flachica** [comment]
Lo revisaremos pero te adelanto que Tasker se basa en todotxt.org. Un formato propuesto para ser extramademente simple y portable. Pero esto tiene un precio, y es que no soporta ciertos aspectos como que un proyecto pueda contener espacios o caracteres que se salgan del estándar de condificación genérico.

Muchas gracias por el aporte. Lo tendremos muy en cuenta.

**Comment by atareao** [comment]
Fixed in 0.4.0 Gracias @Montsemg
