### ISSUE TITLE
Project with spaces in name not saved

### ISSUE THREAD

**Issue by flachica** [atareao/todotxt-indicator#2]
If save task related with project with spaces in the name, the task will be assigned to one new project  with the first word of the original name. 

1 .- Save project with spaces
2 .- Assign new task (todo.txt has correct project set)
3 .- Go to task and try to filter project with spaces in name and not find anything
4 .- Close and open Tasker and show new project

**Comment by atareao** [comment]
Fixed. Only alphanumeric characters for projects and context. If non alphanumeric character used is replaced by "_"
