### ISSUE TITLE
No redimensiona los objetos al cambiar el tamaño de la ventana

### ISSUE THREAD

**Issue by damufo** [atareao/todotxt-indicator#23]
Hola:
Acabo de actualizar con la nueva versión.
Hace semanas informé de que las ventanas no redimensionaban. Ahora ya redimensionan pero el problema es que los controles/objetos internos no se redimensionan.

El S. O. es Xubuntu 20.04

Muchas gracias.

![Captura de pantalla_2020-05-18_08-51-02](https://user-images.githubusercontent.com/4057369/82183243-e4b19f00-98e5-11ea-9339-e53402e1d31d.png)

![Captura de pantalla_2020-05-18_08-52-35](https://user-images.githubusercontent.com/4057369/82183250-e8452600-98e5-11ea-838e-57006f954806.png)

**Comment by damufo** [comment]
Solo avisar que esto sigue igual en la versión: 0.4.3-0extras20.04.2

**Comment by atareao** [comment]
Muchas gracias @damufo este issue está resueldo en la versión 0.4.3-0extras20.04.3 que está ya en los repositorios

**Comment by damufo** [comment]
Hola @atareao, siento ser pesado, pero sigue sin funcionar.
La ventana Tarea ahora el contenido lo redimensiona a lo ancho pero no a lo alto y Tareas sigue igual, no redimensiona los controles en ningún sentido.
Solo pasa en XFCE??

![Captura de pantalla_2020-05-28_11-33-24](https://user-images.githubusercontent.com/4057369/83125000-31ac2700-a0d7-11ea-806f-ac076de4e4cf.png)

**Comment by atareao** [comment]
Para nada eres pesado. Todo lo contrario, es de agradecer él tiempo que dedicas a reportar los errores. Muchas gracias
Ahora bien... No se comporta como antes, ahora ya redimensiona parte.
Queda menos 😂😂
Se ve así en todos los escritorios. Lo corrijo, la de donde está él problema.
Muchas gracias por tu tiempo

**Comment by damufo** [comment]
Hola:
Confirmo que ya redimensiona correctamente.
Muchas gracias.

**Comment by atareao** [comment]
Gracias @damufo
