### ISSUE TITLE
Múltiples iconos en la barra de tareas

### ISSUE THREAD

**Issue by Adrian-Benavente** [atareao/todotxt-indicator#24]
La app se puede abrir en múltiples instancias y cada una de ellas genera un ícono en la barra de tareas.

Escenario: Abro Tasker desde el lanzador de aplicaciones mútiples veces, por cada una se genera un ícono en la bandeja del sistema.

Comportamiento esperado: Que la app solo se pueda abrir una única vez, ya que no es de mucha utilidad en este tipo de herramientas tener multiples instancias.

Entorno: KDE Neon

![2020-05-20_18-11](https://user-images.githubusercontent.com/11258517/82498222-01a4c880-9ac6-11ea-9d15-ceabef3d9fc6.png)

**Comment by atareao** [comment]
Fixed in tasker 0.4.1.
Gracias por tu ayuda. En unas horas estará en los repositorios oficiales para actualizar.
Saludos.
